apiVersion: v1
kind: Service
metadata:
  name: {{ include "jetty.fullname" . }}
  labels:
{{ include "jetty.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.httpservice.port }}
      targetPort: http
      protocol: TCP
      name: http
    - port: {{ .Values.httpsservice.port }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/name: {{ include "jetty.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
