version: "3.7"
services:
  mydb:
    image: "mysql"
    networks:
      - appnetwork
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mydb
      - MYSQL_USER=sessusr
      - MYSQL_PASSWORD=sessusr
      - MYSQL_DATABASE=sessdb
  myappsrv1:
    image: "jetty"      
    networks:
      - appnetwork
    depends_on:
      - mydb
    volumes:
      - ./volumes/jetty/config/myappsrv1/session-store-jdbc.ini:/var/lib/jetty/start.d/session-store-jdbc.ini
      - ./volumes/jetty/lib/ext/mysql-connector-java-8.0.20.jar:/var/lib/jetty/lib/ext/mysql-connector-java-8.0.20.jar
      - ./volumes/jetty/webapps:/var/lib/jetty/webapps
    ports:
      - "8080:8080"
  myappsrv2:
    image: "jetty"      
    networks:
      - appnetwork
    depends_on:
      - mydb
      - myappsrv1
    volumes:
      - ./volumes/jetty/config/myappsrv2/session-store-jdbc.ini:/var/lib/jetty/start.d/session-store-jdbc.ini
      - ./volumes/jetty/lib/ext/mysql-connector-java-8.0.20.jar:/var/lib/jetty/lib/ext/mysql-connector-java-8.0.20.jar
      - ./volumes/jetty/webapps:/var/lib/jetty/webapps
    ports:
      - "8081:8080"
  mywebsrv:
    build: . 
    networks:
      - appnetwork
    depends_on:
      - myappsrv1
      - myappsrv2
    volumes:
      - ./volumes/apache2/sites-available:/etc/apache2/sites-available
      - ./volumes/apache2/sslkeys:/etc/apache2/ssl
    ports:
      - "80:80"
      - "443:443"
networks:
  appnetwork:
    name: mynetwork
