apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "jetty.fullname" . }}
  labels:
{{ include "jetty.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "jetty.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "jetty.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.service.internalPort }}
              protocol: TCP
          volumeMounts:
            - name: webappdir
              mountPath: {{ .Values.deploy.jetty_base }}/{{ .Values.deploy.directory }}
      volumes:
        - name: webappdir
          hostPath:
            path: {{ .Values.deploy.hostPath }}
            type: Directory
